const APIBASEURL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';
const BASERESOURCEURL =  'http://localhost:8000';

export const RESOURCE_URL = {
  DOCS: `${BASERESOURCEURL}/Docs`,
};


export const APIURL = {
  ROOT: APIBASEURL,
  ME: `${APIBASEURL}/dashboard`,
  LOGIN: `${APIBASEURL}/login`,
  REGISTER: `${APIBASEURL}/register`,
  LOGOUT: `${APIBASEURL}/logout`,
  UTILISATEURS: `${APIBASEURL}/v1/utilisateurs`,
  SOCIETES: `${APIBASEURL}/v1/societes`,
  TYPEPROJETS: `${APIBASEURL}/v1/typeProjets`,
  TYPEBIENS: `${APIBASEURL}/v1/typeBiens`,
  TYPEFREINS: `${APIBASEURL}/v1/typefreins`,
  BANQUES: `${APIBASEURL}/v1/banques`,
  VUES: `${APIBASEURL}/v1/vues`,
  TYPOLOGIES: `${APIBASEURL}/v1/typologies`,
  SOURCES: `${APIBASEURL}/v1/sources`,
  PARTENAIRES: `${APIBASEURL}/v1/partenaires`,
  PROJETS: `${APIBASEURL}/v1/projets`,
  TRANCHES: `${APIBASEURL}/v1/tranches`,
  BLOCS: `${APIBASEURL}/v1/blocs`,
  IMMEUBLES: `${APIBASEURL}/v1/immeubles`,
  BIENS: `${APIBASEURL}/v1/biens`,
  COMPOSITIONBIENS: `${APIBASEURL}/v1/compositionBiens`,
  VISITES: `${APIBASEURL}/v1/visites`,
  ENCAISSEMENTS: `${APIBASEURL}/v1/encaissements`,
  APPELS: `${APIBASEURL}/v1/appels`,
  ROOTV1: `${APIBASEURL}/v1`,
  PROSPECTS: `${APIBASEURL}/v1/prospects`,
  CLIENTS: `${APIBASEURL}/v1/clients`,
  PAIEMENTS:`${APIBASEURL}/v1/avances`,
  DESISTEMENT:`${APIBASEURL}/v1/desistements`,
  OBJECTIFS: `${APIBASEURL}/v1/objectifs`,
  RESERVATIONS: `${APIBASEURL}/v1/reservations`,
  FOURNISSEURS: `${APIBASEURL}/v1/fournisseurs`,
  DECOMPTES: `${APIBASEURL}/v1/decomptes`,
  FACTURES: `${APIBASEURL}/v1/factures`,
  CPS: `${APIBASEURL}/v1/cps`,
  CREDITS:`${APIBASEURL}/v1/credits`,
  ServicesPrestataires:`${APIBASEURL}/v1/ServicesPrestataires`,
  Prestataires:`${APIBASEURL}/v1/Prestataires`,
  ReclamationsSav:`${APIBASEURL}/v1/ReclamationsSav`,
  ReclamationsClient:`${APIBASEURL}/v1/ReclamationsClients`,
  REMISECLES:`${APIBASEURL}/v1/RemiseCles`,
  ECHEANCESTRANCE:`${APIBASEURL}/v1/EcheancesTranche`,
  ETAPESPROJET:`${APIBASEURL}/v1/etapesProjet`,
  COMMISSIONS: `${APIBASEURL}/v1/commissions`,
  COMMISSSIONCONFIG: `${APIBASEURL}/v1/commisssionConfig`, // Using the exact same spelling with three S's
  COMMISSIONSCONFIGURATIONS: `${APIBASEURL}/v1/commissionsConfigurations`,
}

export const ENDPOINTS = {
  API: process.env.NEXT_PUBLIC_API_URL,
  HOME: '/home',
  UTILISATEURS: '/utilisateurs/home',
  SOCIETES: '/societes/home',
  TYPEPROJETS: '/administration/typeProjets',
  TYPEBIENS: '/administration/typeBiens',
  BANQUES: '/administration/banques',
  VUES: '/administration/vues',
  TYPOLOGIES: '/administration/typologies',
  TYPEFREINS: '/administration/freins',
  SOURCES: '/administration/sources',
  PARTENAIRES: '/administration/partenaires',
  PROJETS: '/projets/home',
  TRANCHES: '/tranches/home',
  BLOCS: '/blocs/home',
  IMMEUBLES: '/immeubles/home',
  BIENS: '/biens/home',
  COMPOSITIONBIENS: '/compositionBiens/home',
  VISITES: '/crm/visites',
  APPELS: '/crm/appels',
  PROSPECTS: '/CRM/Prospects',
  CLIENTS: '/clients/home',
  ENCAISSEMENTS: '/encaissements/home',
  RESERVATIONS: '/reservations/home',
  TVA: '/tva/home',
  DESISTEMENT:'/desistements/home',
  PAIEMENTS:'/paiements/home',
  OBJECTIFS:'/administration/objectifs',
  FOURNISSEURS: '/fournisseurs/home',
  DECOMPTES: '/decomptes/home',
  FACTURES: '/factures/home',
  CPS:'/cps/home',
  CREDITS:'/credits/home',
  ServicesPrestataires:'/ServicesPrestataires/home',
  Prestataires:'/Prestataires/home',
  ReclamationsSav:'/reclamationsSav/home',
  ReclamationsClients:'/reclamationsClients/home',
  REMISECLES:'/remiseCles/home',
  ECHEANCESTRANCE:'/echeancesTranche/home',
  HISTOIMPORTATION:'/histoImportation/home',
  ETAPESPROJET:'/etapesProjet/home',
}

